name: pest

on:
  push:

jobs:
  pest:
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - run: vendor/bin/pest
